/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppStaffRouteImport } from './routes/_app.staff'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRunnerRouteImport } from './routes/_app.runner'
import { Route as AppRequestRouteImport } from './routes/_app.request'
import { Route as AppErrandsRouteImport } from './routes/_app.errands'
import { Route as AppDispatchRouteImport } from './routes/_app.dispatch'
import { Route as AppTrackingIdRouteImport } from './routes/_app.tracking.$id'
import { Route as AppChatIdRouteImport } from './routes/_app.chat.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRunnerRoute = AppRunnerRouteImport.update({
  id: '/runner',
  path: '/runner',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestRoute = AppRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => AppRoute,
} as any)
const AppErrandsRoute = AppErrandsRouteImport.update({
  id: '/errands',
  path: '/errands',
  getParentRoute: () => AppRoute,
} as any)
const AppDispatchRoute = AppDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingIdRoute = AppTrackingIdRouteImport.update({
  id: '/tracking/$id',
  path: '/tracking/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIdRoute = AppChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/dispatch': typeof AppDispatchRoute
  '/errands': typeof AppErrandsRoute
  '/request': typeof AppRequestRoute
  '/runner': typeof AppRunnerRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/chat/$id': typeof AppChatIdRoute
  '/tracking/$id': typeof AppTrackingIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/dispatch': typeof AppDispatchRoute
  '/errands': typeof AppErrandsRoute
  '/request': typeof AppRequestRoute
  '/runner': typeof AppRunnerRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/': typeof AppIndexRoute
  '/chat/$id': typeof AppChatIdRoute
  '/tracking/$id': typeof AppTrackingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/dispatch': typeof AppDispatchRoute
  '/_app/errands': typeof AppErrandsRoute
  '/_app/request': typeof AppRequestRoute
  '/_app/runner': typeof AppRunnerRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/': typeof AppIndexRoute
  '/_app/chat/$id': typeof AppChatIdRoute
  '/_app/tracking/$id': typeof AppTrackingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dispatch'
    | '/errands'
    | '/request'
    | '/runner'
    | '/settings'
    | '/staff'
    | '/chat/$id'
    | '/tracking/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/dispatch'
    | '/errands'
    | '/request'
    | '/runner'
    | '/settings'
    | '/staff'
    | '/'
    | '/chat/$id'
    | '/tracking/$id'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/dispatch'
    | '/_app/errands'
    | '/_app/request'
    | '/_app/runner'
    | '/_app/settings'
    | '/_app/staff'
    | '/_app/'
    | '/_app/chat/$id'
    | '/_app/tracking/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runner': {
      id: '/_app/runner'
      path: '/runner'
      fullPath: '/runner'
      preLoaderRoute: typeof AppRunnerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/request': {
      id: '/_app/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof AppRequestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/errands': {
      id: '/_app/errands'
      path: '/errands'
      fullPath: '/errands'
      preLoaderRoute: typeof AppErrandsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dispatch': {
      id: '/_app/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof AppDispatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking/$id': {
      id: '/_app/tracking/$id'
      path: '/tracking/$id'
      fullPath: '/tracking/$id'
      preLoaderRoute: typeof AppTrackingIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/$id': {
      id: '/_app/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AppChatIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDispatchRoute: typeof AppDispatchRoute
  AppErrandsRoute: typeof AppErrandsRoute
  AppRequestRoute: typeof AppRequestRoute
  AppRunnerRoute: typeof AppRunnerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatIdRoute: typeof AppChatIdRoute
  AppTrackingIdRoute: typeof AppTrackingIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDispatchRoute: AppDispatchRoute,
  AppErrandsRoute: AppErrandsRoute,
  AppRequestRoute: AppRequestRoute,
  AppRunnerRoute: AppRunnerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatIdRoute: AppChatIdRoute,
  AppTrackingIdRoute: AppTrackingIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
